site_name: AWS Solution Architect Professional - Concept Notes
repo_url: https://github.com/jeyabalajis/aws-certified-sa-pro-notes.git
theme:
  name: 'material'
  logo: 'images/logo.png'
use_directory_urls: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - pymdownx.superfences
plugins:
    - search
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
nav:
  - Home: index.md
  - Identity & Federation:
      - Identity: identity/identity.md
      - Identity Federation: identity/identity_federation.md
  - Security:
      - CloudTrail: security/cloudtrail.md
      - Keys and Parameters Management: security/keys_parameter_management.md
      - WAF: security/waf.md
      - Mitigate DDoS Attacks: security/ddos_attacks_mitigation.md
      - Guard Duty: security/guard_duty.md
      - Inspector & Config: security/inspector_config.md
      - S3 Security: security/s3_security.md
      - Certificate Manager: certificate_manager.md
  - Networking:
      - Hybrid Networking: network/hybrid_networking.md
      - Advanced Networking: network/advanced_networking.md
      - VPC: network/vpc.md
      - Route 53: network/route53.md
      - CloudFront: network/CloudFront.md
      - Forward Proxy: network/web_proxy.md
  - Storage:
      - EBS: storage/ebs.md
      - EFS: storage/efs.md
      - S3: storage/s3.md
      - CloudFront: storage/cloudfront.md
      - ElastiCache: storage/elasticache.md
  - Migration:
      - Migration: migration/migration.md
      - Discovery Agent: migration/aws_discovery_agent.md
  - Computing:
      - EC2: compute/ec2.md
      - ECS & Lambda: compute/ecs_lambda.md
      - Data Management: compute/data_management.md
      - ELB & API Gateway: compute/elb_apigw_appsync.md
      - AutoScaling: compute/auto_scaling.md
      - Elastic Beanstalk: compute/elastic_bean_stalk.md
      - AppSync: compute/appsync.md
      - WorkDocs: compute/workdocs.md
      - X-Ray: compute/xray.md
      - Application Auto Scaling: compute/application_auto_scaling.md
      - Step Functions: compute/step_functions.md
  - Data Engineering:
      - Data Engineering: data_engineering/data_engineering.md
  - Databases:
      - RDS: databases/rds.md
      - DynamoDB: databases/dynamodb.md
  - Cost Control:
      - Cost Control: cost_control/cost_control.md
      - Trusted Advisor: cost_control/trusted_advisor.md
  - Logging:
      - Logging: logging/logging.md
  - Deployment:
      - Systems Manager: deployment/systems_manager.md
  - Organizations:
      - Organizations: organizations/organizations.md
  - Disaster Recovery:
      - Disaster Recovery: disaster_recovery/disaster_recovery.md
  - Cloud Operations:
      - AWS Config: cloud_ops/aws_config.md
      - Systems Manager: cloud_ops/systems_manager.md      
  - Miscellaneous:
      - Miscellaneous: misc/misc_services.md
  - Exam Preparation:
      - Exam Prep: exam_prep/exam_prep.md
