site_name: AWS Solution Architect Professional - Concept Notes
repo_url: https://github.com/jeyabalajis/aws-certified-sa-pro-notes.git
theme:
  name: 'material'
  logo: 'images/logo.png'
use_directory_urls: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - pymdownx.superfences
plugins:
    - search
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
nav:
  - Home: index.md
  - Identity & Federation:
      - Identity: identity/identity.md
      - Identity Federation: identity/identity_federation.md
  - Security:
      - CloudTrail: security/cloudtrail.md
      - Keys and Parameters Management: security/keys_parameter_management.md
      - Mitigate DDoS Attacks: security/ddos_attacks_mitigation.md
      - Guard Duty: security/guard_duty.md
      - Inspector & Config: security/inspector_config.md
      - S3 Security: security/s3_security.md
  - Networking:
      - Hybrid Networking: network/hybrid_networking.md
      - VPC: network/vpc.md
      - Route 53: network/route53.md
      - CloudFront: network/CloudFront.md
  - Storage:
      - EBS: storage/ebs.md
      - EFS: storage/efs.md
      - S3: storage/s3.md
      - CloudFront: storage/cloudfront.md
      - ElastiCache: storage/elasticache.md
  - Migration:
      - Migration: migration/migration.md
  - Computing:
      - EC2: computing/ec2.md
      - ECS & Lambda: computing/ecs_lambda.md
      - Data Management: computing/data_management.md
      - ELB & API Gateway: computing/elb_apigw_appsync.md
      - Auto-Scaling: computing/autoscaling.md
  - Data Engineering:
      - Data Engineering: data_engineering/data_engineering.md
  - Databases:
      - RDS: databases/rds.md
      - DynamoDB: databases/dynamodb.md
  - Cost Control:
      - Cost Control: cost_control/cost_control.md
  - Logging:
      - Logging: logging/logging.md
  - Exam Preparation:
      - Exam Prep: exam_prep/exam_prep.md
